[target.i686-pc-windows-msvc]
rustflags = [
  "-C", "link-arg=/SAFESEH:NO",
  "-C", "target-feature=+crt-static"
]


[target.armv7-unknown-linux-musleabihf]
linker = "armv7-unknown-linux-musleabihf-gcc"

[target.x86_64-linux-android]
rustflags = [
  "-C", "link-arg=-lgcc"
]

[target.i686-linux-android]
rustflags = [
  "-C", "link-arg=-lgcc"
]


[target.aarch64-apple-ios]
rustflags = [
  "-C", "panic=unwind"
  ]